# Generated by Django 3.0.7 on 2020-06-11 13:34

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_filter', models.CharField(choices=[('sketch', 'Sketch'), ('histogram', 'Histogram'), ('collage', 'Collage'), ('meme', 'Meme')], max_length=10)),
                ('filter_option', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
                ('filter_type', models.CharField(max_length=10, null=True, validators=[images.models.validate_filter])),
                ('filter_options', models.CharField(max_length=200, null=True)),
                ('width', models.IntegerField(null=True)),
                ('height', models.IntegerField(null=True)),
            ],
        ),
    ]
