# Generated by Django 3.0.7 on 2020-06-05 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='filter_options',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='filter_type',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='save',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
