# Generated by Django 3.0.7 on 2020-06-05 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20200605_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
