# Generated by Django 3.0.7 on 2020-06-05 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20200605_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='save',
        ),
    ]
