# Generated by Django 3.0.7 on 2020-06-05 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_image_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='save',
            field=models.BooleanField(),
        ),
    ]
