# Generated by Django 3.0.7 on 2020-06-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_auto_20200605_1240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='save',
        ),
    ]
