# Generated by Django 3.0.7 on 2020-06-05 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_remove_image_save'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filter_options',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
