# Generated by Django 3.0.7 on 2020-06-07 11:23

from django.db import migrations, models
import images.models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_auto_20200605_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='filter_options',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='filter_type',
            field=models.CharField(max_length=10, null=True, validators=[images.models.validate_filter]),
        ),
    ]
