# Generated by Django 3.0.7 on 2020-06-07 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20200607_1123'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_filter', models.CharField(choices=[('none', 'None'), ('sketch', 'Sketch'), ('histogram', 'Histogram'), ('collage', 'Collage'), ('meme', 'Meme')], max_length=10)),
                ('filter_option', models.CharField(max_length=20)),
            ],
        ),
    ]
