# Generated by Django 3.0.7 on 2020-06-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_filter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='filter_option',
            field=models.CharField(max_length=200),
        ),
    ]
