# Generated by Django 3.0.7 on 2020-06-08 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_auto_20200608_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filter',
            name='related_filter',
            field=models.CharField(choices=[('sketch', 'Sketch'), ('histogram', 'Histogram'), ('collage', 'Collage'), ('meme', 'Meme')], max_length=10),
        ),
    ]
