# Generated by Django 3.0.7 on 2020-06-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_auto_20200609_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='url',
            field=models.TextField(),
        ),
    ]
